# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'IQI' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

#pod 'AMapSearch'
pod 'AMap3DMap','~>5.0.0'
# pod 'AMapLocation'
pod 'AFNetworking'
pod 'FMDB'
pod 'MJRefresh'
pod 'MJExtension'
pod 'pop'
pod 'SDWebImage'
pod 'FSCalendar'
pod 'NullSafe'
pod 'IQKeyboardManager'
pod ‘MBProgressHUD’
  # Pods for IQI

end
